# Generated by Django 4.2 on 2023-05-17 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=50)),
                ('spouse_surname', models.CharField(max_length=50)),
                ('spouse_first_name', models.CharField(max_length=50)),
                ('spouse_last_name', models.CharField(max_length=50)),
                ('spouse_national_id', models.CharField(max_length=50)),
                ('spouse_email', models.CharField(max_length=50)),
                ('spouse_phone', models.CharField(max_length=50)),
                ('spouse_city', models.CharField(max_length=50)),
                ('spouse_pob', models.CharField(max_length=50)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pob', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=50)),
                ('father_surname', models.CharField(max_length=50)),
                ('father_first_name', models.CharField(max_length=50)),
                ('father_last_name', models.CharField(max_length=50)),
                ('father_national_id', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('mother_surname', models.CharField(max_length=50)),
                ('mother_first_name', models.CharField(max_length=50)),
                ('mother_last_name', models.CharField(max_length=50)),
                ('mother_national_id', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('guardian_surname', models.CharField(max_length=50)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_initial_name', models.CharField(max_length=50)),
                ('guardian_national_id', models.CharField(max_length=50)),
                ('guardian_email', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=50)),
                ('guardian_city', models.CharField(max_length=50)),
                ('guardian_pob', models.CharField(max_length=50)),
                ('guardian_occupation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInstitutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_institution_name', models.CharField(max_length=50)),
                ('first_institution_specialization', models.CharField(max_length=50)),
                ('first_institution_qualification', models.CharField(max_length=50)),
                ('second_institution_name', models.CharField(max_length=50)),
                ('second_institution_specialization', models.CharField(max_length=50)),
                ('second_institution_qualification', models.CharField(max_length=50)),
                ('third_institution_name', models.CharField(max_length=50)),
                ('third_institution_specialization', models.CharField(max_length=50)),
                ('third_institution_qualification', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_impairment', models.CharField(max_length=50)),
                ('physical_impairment_details', models.CharField(max_length=50)),
                ('other_information', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NextKinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nxtk_surname', models.CharField(max_length=50)),
                ('nxtk_first_name', models.CharField(max_length=50)),
                ('nxtk_initial_name', models.CharField(max_length=50)),
                ('nxtk_national_id', models.CharField(max_length=50)),
                ('nxtk_email', models.CharField(max_length=50)),
                ('nxtk_phone', models.CharField(max_length=50)),
                ('nxtk_city', models.CharField(max_length=50)),
                ('nxtk_pob', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_high_school_name', models.CharField(max_length=50)),
                ('first_high_school_address', models.CharField(max_length=50)),
                ('first_high_school_town', models.CharField(max_length=50)),
                ('first_high_school_from_date', models.CharField(max_length=50)),
                ('first_high_school_to_date', models.CharField(max_length=50)),
                ('second_high_school_name', models.CharField(max_length=50)),
                ('second_high_school_address', models.CharField(max_length=50)),
                ('second_high_school_town', models.CharField(max_length=50)),
                ('second_high_school_from_date', models.CharField(max_length=50)),
                ('second_high_school_to_date', models.CharField(max_length=50)),
                ('third_high_school_name', models.CharField(max_length=50)),
                ('third_high_school_address', models.CharField(max_length=50)),
                ('third_high_school_town', models.CharField(max_length=50)),
                ('third_high_school_from_date', models.CharField(max_length=50)),
                ('third_high_school_to_date', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_and_sports', models.CharField(max_length=50)),
                ('games_representation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('medical', models.FileField(upload_to='')),
                ('sporting', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerge_con_surname', models.CharField(max_length=50)),
                ('emerge_con_first_name', models.CharField(max_length=50)),
                ('emerge_con_initial_name', models.CharField(max_length=50)),
                ('emerge_con_national_id', models.CharField(max_length=50)),
                ('emerge_con_email', models.CharField(max_length=50)),
                ('emerge_con_phone', models.CharField(max_length=50)),
                ('emerge_con_city', models.CharField(max_length=50)),
                ('emerge_con_pob', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_club', models.CharField(max_length=50)),
                ('second_club', models.CharField(max_length=50)),
                ('third_club', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
