# Generated by Django 4.2.1 on 2023-05-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalDetails',
            new_name='PersonalDetail',
        ),
    ]
