# Generated by Django 4.2 on 2023-05-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_personaldetail_student_personaldetail_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
