# Generated by Django 4.2 on 2023-05-12 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=50)),
                ('father_surname', models.CharField(max_length=50)),
                ('father_first_name', models.CharField(max_length=50)),
                ('father_last_name', models.CharField(max_length=50)),
                ('father_national_id', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('mother_surname', models.CharField(max_length=50)),
                ('mother_first_name', models.CharField(max_length=50)),
                ('mother_last_name', models.CharField(max_length=50)),
                ('mother_national_id', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('guardian_surname', models.CharField(max_length=50)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_initial_name', models.CharField(max_length=50)),
                ('guardian_national_id', models.CharField(max_length=50)),
                ('guardian_email', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=50)),
                ('guardian_city', models.CharField(max_length=50)),
                ('guardian_pob', models.CharField(max_length=50)),
                ('guardian_occupation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
