# Generated by Django 4.2 on 2023-05-13 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0004_parentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=50)),
                ('spouse_surname', models.CharField(max_length=50)),
                ('spouse_first_name', models.CharField(max_length=50)),
                ('spouse_last_name', models.CharField(max_length=50)),
                ('spouse_national_id', models.CharField(max_length=50)),
                ('spouse_email', models.CharField(max_length=50)),
                ('spouse_phone', models.CharField(max_length=50)),
                ('spouse_city', models.CharField(max_length=50)),
                ('spouse_pob', models.CharField(max_length=50)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
