# Generated by Django 4.2 on 2023-05-13 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0005_spousedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextKinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nxtk_surname', models.CharField(max_length=50)),
                ('nxtk_first_name', models.CharField(max_length=50)),
                ('nxtk_initial_name', models.CharField(max_length=50)),
                ('nxtk_national_id', models.CharField(max_length=50)),
                ('nxtk_email', models.CharField(max_length=50)),
                ('nxtk_phone', models.CharField(max_length=50)),
                ('nxtk_city', models.CharField(max_length=50)),
                ('nxtk_pob', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
