# Generated by Django 4.2 on 2023-05-13 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0006_nextkindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_high_school_name', models.CharField(max_length=50)),
                ('first_high_school_address', models.CharField(max_length=50)),
                ('first_high_school_town', models.CharField(max_length=50)),
                ('first_high_school_from_date', models.CharField(max_length=50)),
                ('first_high_school_to_date', models.CharField(max_length=50)),
                ('second_high_school_name', models.CharField(max_length=50)),
                ('second_high_school_address', models.CharField(max_length=50)),
                ('second_high_school_town', models.CharField(max_length=50)),
                ('second_high_school_from_date', models.CharField(max_length=50)),
                ('second_high_school_to_date', models.CharField(max_length=50)),
                ('third_high_school_name', models.CharField(max_length=50)),
                ('third_high_school_address', models.CharField(max_length=50)),
                ('third_high_school_town', models.CharField(max_length=50)),
                ('third_high_school_from_date', models.CharField(max_length=50)),
                ('third_high_school_to_date', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
