# Generated by Django 4.2 on 2023-05-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0007_highschooldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerge_con_surname', models.CharField(max_length=50)),
                ('emerge_con_first_name', models.CharField(max_length=50)),
                ('emerge_con_initial_name', models.CharField(max_length=50)),
                ('emerge_con_national_id', models.CharField(max_length=50)),
                ('emerge_con_email', models.CharField(max_length=50)),
                ('emerge_con_phone', models.CharField(max_length=50)),
                ('emerge_con_city', models.CharField(max_length=50)),
                ('emerge_con_pob', models.CharField(max_length=50)),
                ('emerge_con_occupation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
