# Generated by Django 4.2 on 2023-05-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_emergencycontactdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontactdetail',
            name='emerge_con_occupation',
        ),
    ]
