# Generated by Django 4.2 on 2023-05-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_gamesdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesdetail',
            old_name='games_represenation',
            new_name='games_representation',
        ),
    ]
