# Generated by Django 4.2 on 2023-05-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0012_clubsdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInstitutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_institution_name', models.CharField(max_length=50)),
                ('first_institution_specialization', models.CharField(max_length=50)),
                ('first_institution_qualification', models.CharField(max_length=50)),
                ('second_institution_name', models.CharField(max_length=50)),
                ('second_institution_specialization', models.CharField(max_length=50)),
                ('second_institution_qualification', models.CharField(max_length=50)),
                ('third_institution_name', models.CharField(max_length=50)),
                ('third_institution_specialization', models.CharField(max_length=50)),
                ('third_institution_qualification', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
